# Generated by Django 3.1.7 on 2021-03-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('symbol', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='DSR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('failed', 'FAILED'), ('ingested', 'INGESTED')], default='failed', max_length=48)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.currency')),
            ],
            options={
                'db_table': 'dsr',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('code_2', models.CharField(max_length=2)),
                ('code_3', models.CharField(max_length=3)),
                ('local_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='dsrs.currency')),
            ],
            options={
                'verbose_name': 'territory',
                'verbose_name_plural': 'territories',
                'db_table': 'territory',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('dsp_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('artists', models.CharField(blank=True, max_length=256)),
                ('isrc', models.CharField(blank=True, max_length=16)),
                ('usages', models.IntegerField(null=True)),
                ('revenue', models.FloatField(null=True)),
                ('dsr', models.ManyToManyField(to='dsrs.DSR')),
            ],
        ),
        migrations.AddField(
            model_name='dsr',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.territory'),
        ),
    ]
