# Generated by Django 3.1.7 on 2021-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='artists',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='isrc',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
