# Generated by Django 3.1.7 on 2021-03-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0002_auto_20210316_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='dsr',
            new_name='dsrs',
        ),
    ]
