# Generated by Django 3.1.7 on 2021-03-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0003_auto_20210316_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='artists',
            field=models.CharField(help_text='Multivalue, pipe-separated list of artist names.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dsrs',
            field=models.ManyToManyField(help_text='List of DSRs on which the resource is reported.', to='dsrs.DSR'),
        ),
    ]
